services:
  - type: web
    name: whatsapp-reply-checker
    runtime: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
